### ISSUE TITLE
OTLP Reporter

### ISSUE THREAD

**Issue by braunsonm** [micrometer-metrics/tracing#156]
Hello,

I haven't been able to find a clear answer to this so I thought I would request it here. Is there a reason why Micrometer does not seem to support an Opentelemetry OTLP reporter for traces? There are various bridges to create Opentelemetry traces which can be converted by reporters to zipkin and wavefront, but is there a reason why simply reporting to OTLP is not supported yet?

From my point of view, my tracing front end (tempo) supports OTLP traces directly, so I don't need the extra overhead of converting to a zipkin or wavefront brave format.

It looks like micromter-metrics supports this for `MeterRegistry` but haven't seen any work on the same thing for traces: https://github.com/micrometer-metrics/micrometer/commit/234e58bb45439b4318628e22d093a20eb1302fd3

**Comment by jonatan-ivanov** [comment]
The OTLP support in Micrometer and Micrometer Tracing has some differences because of he goal of the project and the history of them.
In short: Micrometer is a metrics library, it produces the outputs on its own while Micrometer Tracing is an abstraction over tracing libraries (brave and OTel), it does not produce the output on its own, it delegates this to the tracing libraries.

So if you want to use OTLP with Micrometer Tracing and the OTel bridge, check this section of the docs: https://micrometer.io/docs/tracing#_micrometer_tracing_opentelemetry_setup and replace the `SpanExporter` so that it won't export traces in Zipkin but in OTLP format.
The `SpanExporter` interface comes from OTel as well as all of the implementations (e.g.: [OTLP](https://github.com/open-telemetry/opentelemetry-java/tree/main/exporters/otlp)), that's we we don't provide it.

**Comment by braunsonm** [comment]
Thank you for the detailed response and explanation @jonatan-ivanov 

I'll open an issue with spring since it is wiring the `SpanExporter` for me in my case.
