### ISSUE TITLE
How to set traceId/SpanId with an existing value

### ISSUE THREAD

**Issue by krshna-dtdl** [micrometer-metrics/tracing#267]
How to achieve this in spring 3 micrometer
https://github.com/spring-cloud/spring-cloud-sleuth/issues/1152

**Comment by jonatan-ivanov** [comment]
The repo you originally opened this issue for is Micrometer, I think this belongs to Micrometer Tracing (so I moved the issue).

The issue you linked is very old (Sleuth 2.x timeline) where Sleuth used Brave so what you see there is basically how to do it in Brave. That method is still available.

But my question really is: why do you want to do this? If this is because you want to extract the tracing information from some kind of request/message headers (e.g.: http), Boot already supports that. If you have something custom/not supported, pease take a look at the propagator mechanism (I think they do what you need):
- [`PropagatingReceiverTracingObservationHandler`](https://github.com/micrometer-metrics/tracing/blob/main/micrometer-tracing/src/main/java/io/micrometer/tracing/handler/PropagatingReceiverTracingObservationHandler.java)
- [`BravePropagator`](https://github.com/micrometer-metrics/tracing/blob/main/micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/main/java/io/micrometer/tracing/brave/bridge/BravePropagator.java)

See this part, once you have the 
```
TraceContextOrSamplingFlags extracted = tracing.propagation().extractor(getter::get).extract(carrier);
BraveSpanBuilder.toBuilder(tracing.tracer(), extracted);
```
