### ISSUE TITLE
Support for SQS sendMessage and sendMessageBatch

### ISSUE THREAD

**Issue by teammakdi** [micrometer-metrics/tracing#295]
Hi, I'm having a spring boot 3 project with micrometer tracing, using opentelemetry with gRPC exporter to Jaeger.

Imported dependencies

```xml
<dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>micrometer-tracing-bridge-otel</artifactId>
</dependency>
<dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-exporter-otlp</artifactId>
</dependency>
```

Was wondering how can I trace a log between 2 applications having a AWS SQS queue in between. (Tried tracing with Apache Kafka queue, works as expected).

**Comment by teammakdi** [comment]
@marcingrzejszczak

**Comment by marcingrzejszczak** [comment]
Thanks for filing the issue. Why are you filing the issue here in Micrometer Tracing? You should file an issue in the project that you're using for AWS SQS instrumentation to support Micrometer Observation API. That way things will work out of the box (you can add me in cc of such an issue - we can help write the instrumentation).
