### ISSUE TITLE
How to propagate traceId & spanId from request to response for reactor netty?

### ISSUE THREAD

**Issue by doljae** [micrometer-metrics/tracing#414]
# Expected result

- I want to make simple architecture using Spring with observation feature using `micrometer-tracing`.
```mermaid
graph TD;
  subgraph System architecture
    A[kopring-gateway] --> B[kopring-api]
  end
```
- I want to log the `traceId` and `spanId` of Spring Cloud Gateway's Request API request by propagating them to the response.
- I added a custom filter for logging both request and response from gateway application with wrapping response to [ServerHttpResponseDecorator](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/server/reactive/ServerHttpResponseDecorator.html).

```kotlin
@Component
class LoggingFilter(private val tracer: Tracer) : WebFilter, Ordered {

    private val logger = LoggerFactory.getLogger(LoggingFilter::class.java)

    override fun filter(exchange: ServerWebExchange, chain: WebFilterChain): Mono<Void> {
        val request = exchange.request

        val traceId = tracer.currentSpan()!!.context().traceId()
        val spanId = tracer.currentSpan()!!.context().spanId()

        logger.info(
            "Request: method={},uri={},headers={},traceId={},spanId={}",
            request.method,
            request.uri,
            request.headers,
            traceId,
            spanId,
        )

        val responseDecorator = object : ServerHttpResponseDecorator(exchange.response) {
            override fun setStatusCode(@Nullable status: HttpStatusCode?): Boolean {
                logger.info(
                    "Response: statusCode={},headers={},traceId={},spanId={}",
                    statusCode,
                    headers,
                    traceId,
                    spanId,
                )

                return super.setStatusCode(statusCode)
            }
        }

        return chain.filter(exchange.mutate().response(responseDecorator).build())
    }

    override fun getOrder(): Int {
        return -1
    }
}
```

# Current result

- For request logs, `traceId` and `spanId` are normally output in the log pattern.
- However, for response logs, `traceId` and `spanId` are not displayed.

# Reproduction

[Demo project](https://github.com/doljae/kopring-template/tree/feature/tracing)(branch: `feature/tracing`)
1. Run `docker-compose.yml`
2. Run `kopring-gateway` & `kopring-api` application
3. Request test API below...
```shell
curl localhost:1234/kopring/test
```

### Result
```shell
2023-10-21T17:11:00.815+09:00  INFO [kopring-gateway,,] [main] 10269 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port 1234
2023-10-21T17:11:00.846+09:00  INFO [kopring-gateway,,] [main] 10269 --- [           main] c.k.gateway.KopringGatewayApplicationKt  : Started KopringGatewayApplicationKt in 1.208 seconds (process running for 1.417)
2023-10-21T17:11:03.586+09:00  INFO [kopring-gateway,6533879763deeb804778cf2b63d4cb55,4778cf2b63d4cb55] [reactor-http-nio-2] 10269 --- [ctor-http-nio-2] com.kopring.gateway.LoggingFilter        : Request: method=GET,uri=http://localhost:1234/kopring/test,headers=[Host:"localhost:1234", User-Agent:"curl/8.1.2", Accept:"*/*"],traceId=6533879763deeb804778cf2b63d4cb55,spanId=4778cf2b63d4cb55
2023-10-21T17:11:03.872+09:00  INFO [kopring-gateway,,] [reactor-http-nio-2] 10269 --- [ctor-http-nio-2] com.kopring.gateway.LoggingFilter        : Response: statusCode=200 OK,headers=[transfer-encoding:"chunked"],traceId=6533879763deeb804778cf2b63d4cb55,spanId=4778cf2b63d4cb55
```

# Additional information

- I want to know if there is an option or configuration in `micrometer-tracing` that has the [same effect as `DECORATE_QUEUES` in Sleuth](https://docs.spring.io/spring-cloud-sleuth/docs/current-SNAPSHOT/reference/html/integrations.html#sleuth-reactor-integration).

**Comment by jonatan-ivanov** [comment]
Please make sure that you have in both apps and that is called `Hooks.enableAutomaticContextPropagation()` (e.g.: test are not always calling `main`).

It would also be great to use Java for the reproduces so that we can rule out the Kotlin related things.

>However, for response logs, traceId and spanId are not displayed.

Could you please check that the instrumentation in Gateway puts your logic into scope? You need to debug the gateway instrumentation for this. (You can also open a scope on your own to test things.) Also, do you have any clue that suggests that this is a Micrometer Tracing issue and not an issue with the Gateway instrumentation?

>I want to know if there is an option or configuration in micrometer-tracing that has the [same effect as DECORATE_QUEUES in Sleuth](https://docs.spring.io/spring-cloud-sleuth/docs/current-SNAPSHOT/reference/html/integrations.html#sleuth-reactor-integration).

Not really since that approach had issues. Reactor is instrumented using the context propagation API and the observation API which should make context propagation work better than decorate-queues.

**Comment by doljae** [comment]
@jonatan-ivanov 
> Please make sure that you have in both apps and that is called Hooks.enableAutomaticContextPropagation() (e.g.: test are not always calling main).

`kopring-api` is Spring Web MVC project, so it does not have reactor related dependency. So I can't use it

> It would also be great to use Java for the reproduces so that we can rule out the Kotlin related things.

I agree. I'll try with Java and check it reproduce a result same as Kotlin version one.

> Could you please check that the instrumentation in Gateway puts your logic into scope? You need to debug the gateway instrumentation for this. (You can also open a scope on your own to test things.) Also, do you have any clue that suggests that this is a Micrometer Tracing issue and not an issue with the Gateway instrumentation?

OK. I'll check it with debugger. As you may have guessed, I am a newbie for this area and there's no special clues that this is a Micrometer Tracing issue 😓 

After writing it in Java, I'll check it using a debugger and see which part is the issue.

**Comment by doljae** [comment]
If I find some clue that the issue maybe from Micrometer Tracing side, I'll re-open the issue and come back with new comment 🙂 

Thanks for your detailed comment @jonatan-ivanov .

(PS, If you already know the answer or point that I missed, it will be really helpful 🙏 )

**Comment by jonatan-ivanov** [comment]
I'm not sure if koping-api being mvc matters, since as far as I understand you have issues with Gateway which uses webflux (also `WebFilter` is from webflux) too.

There is only one thing that comes to my mind: maybe your `WebFilter` is executed before the filter that creates the observation: [`ServerHttpObservationFilter`](https://github.com/spring-projects/spring-framework/blob/d6c9ed200ab9f753940d696c9b0ce2369ebc6e92/spring-web/src/main/java/org/springframework/web/filter/reactive/ServerHttpObservationFilter.java)

Check both filter with your debugger to see the order of execution. In your filter you should be able to get the current observation from the observation registry.
