### ISSUE TITLE
Is there a performance comparison for enabling Reactor's Context Propagation feature?

### ISSUE THREAD

**Issue by doljae** [micrometer-metrics/tracing#415]
# Question

Is there a performance comparison for enabling Reactor's Context Propagation feature?

# Additional info

I've seen a few official articles about this feature, but I haven't found anything specific about how much of a performance impact it has.

- [From Spring blog](https://spring.io/blog/2023/03/30/context-propagation-with-project-reactor-3-unified-bridging-between-reactive)
- [micrometer-tracing Spring Cloud Sleuth 3.1 Migration Guide](https://github.com/micrometer-metrics/tracing/wiki/Spring-Cloud-Sleuth-3.1-Migration-Guide#log-pattern)

If anyone has any data on this, I'd love to know.

**Comment by jonatan-ivanov** [comment]
In Micrometer Tracing?
Since neither context propagation nor Reactor is hosted in this repo, I would say the question is not really applicable.

In Reactor? I'm pretty sure there is a difference (might not be big or measurable) but I think you want to ask this question in Reactor channels. (/cc @chemicL)
We have benchmarks for Micrometer Tracing but we are not benchmarking Reactor or other libraries that instrument themselves using Micrometer modules.

**Comment by chemicL** [comment]
PTAL https://github.com/spring-projects/spring-boot/issues/34201#issuecomment-1754762953

**Comment by doljae** [comment]
Thanks for your clear and detailed comment @jonatan-ivanov 🙂 

As you might have guessed, I'm a newbie in this area and have been struggling with the recent changes to tracing in Spring Boot 3.

Your response helped me understand the points I need to check. Thanks 👍

**Comment by doljae** [comment]
I'll check the issue you linked. Thanks @chemicL 🙂

**Comment by chemicL** [comment]
I actually just meant the linked comment :)
