### ISSUE TITLE
Invalid / outdated documentation and examples

### ISSUE THREAD

**Issue by chechoochoo** [micrometer-metrics/tracing#506]
The original https://github.com/spring-cloud/spring-cloud-sleuth did the typical magic spring modules do, wrapped in spring-boot's auto-configuration - it just worked in servlet-based components, reactive, messaging (amqp, kafka), you name it.

Migration to micrometer (tracing) is still an issue:

- frequent (and sometimes breaking) changes to the micrometer API,
- missing auto-configuration for certain modules (amqp, kafka i.e.)
- issues with reactor (mostly adjusted with spring framework 6.1 and boot 3.2.x)

The biggest problem from a team doing the migration or keeping up with dependencies is lack of / outdated documentation 😢 

Just to name some:

- https://github.com/micrometer-metrics/tracing/wiki/Spring-Cloud-Sleuth-3.1-Migration-Guide#async-instrumentation was adjusted based on an issue (https://github.com/spring-projects/spring-boot/issues/34622); now it points to deprecated code, while there is no information why it is deprecated and what is the alternative
- https://github.com/micrometer-metrics/tracing/issues/372 does not state about the impact and alternative
- a lot of questions about "how to wire it up" / "trace is lost" under https://stackoverflow.com/questions/tagged/micrometer-tracing
- outdated / not complete examples in https://github.com/micrometer-metrics/micrometer-samples
- documentation spread across different projects, with different level of maturity

all in all - it is really hard to have some overview:

- which documentation I need to study when I bump SB dependencies?
  - how those "observability" components are really correlated?
- what to do if something stopped working after migration (_is it micrometer issue? spring-core, spring-boot or some other dependency?_)

Within this issue I mainly wanted to bring awareness to the problem, but also asking for advise - based on points mentioned above, do I miss something obvious and the problem (maybe) does not exist 🤔 ? otherwise - I am eager to contribute but here I would also need some guidance.

**Comment by marcingrzejszczak** [comment]
Hey @chechoochoo, thank you for your issue.

> The original https://github.com/spring-cloud/spring-cloud-sleuth did the typical magic spring modules do, wrapped in spring-boot's auto-configuration - it just worked in servlet-based components, reactive, messaging (amqp, kafka), you name it.

Thank you for your kind words! The problem with Sleuth and reactive was that it didn't do reactive properly - it's full of bugs and memory leaks.

> frequent (and sometimes breaking) changes to the micrometer API,

I don't recall doing breaking changes, can you name some?

> missing auto-configuration for certain modules (amqp, kafka i.e.)

They are being done progressively, I think that both amqp and kafka are already done.

> issues with reactor (mostly adjusted with spring framework 6.1 and boot 3.2.x)

We are working on these. Believe me, the topic is very difficult and will require still some time to work properly. I'll state it again, it didn't work well with Sleuth.

> https://github.com/micrometer-metrics/tracing/wiki/Spring-Cloud-Sleuth-3.1-Migration-Guide#async-instrumentation was adjusted based on an issue (https://github.com/spring-projects/spring-boot/issues/34622); 

That's how it is, sometimes I forget to add things and then when an issue is filed I fix them :)

> now it points to deprecated code, while there is no information why it is deprecated and what is the alternative

What is the deprecated code exactly?

> https://github.com/micrometer-metrics/tracing/issues/372 does not state about the impact and alternative

Because this is not used at all in e.g. Boot and is not maintainable in the long run. Are you actually using this?

> a lot of questions about "how to wire it up" / "trace is lost" under https://stackoverflow.com/questions/tagged/micrometer-tracing

That only proves that the project gets traction. I don't know how I should comment on this one.

> outdated / not complete examples in https://github.com/micrometer-metrics/micrometer-samples

Why are they outdated, why aren't they completed? Can you elaborate on this one? We will not add all possible examples there really.

> documentation spread across different projects, with different level of maturity

What does it even mean? Documentation of what? Which projects are immature?

> which documentation I need to study when I bump SB dependencies? 

I have no idea what you are referring to? What do you want to bump?

>     how those "observability" components are really correlated?

What do you mean by how they are correlated?

> what to do if something stopped working after migration (is it micrometer issue? spring-core, spring-boot or some other dependency?)

It depends on what is not working. It's really hard to answer your question.

> Within this issue I mainly wanted to bring awareness to the problem, but also asking for advise - based on points mentioned above, do I miss something obvious and the problem (maybe) does not exist 🤔 ? otherwise - I am eager to contribute but here I would also need some guidance.

Again, thanks for asking the question. We'll try to answer all of your concerns and find solutions to your problems.
