### ISSUE TITLE
How to setup to consider probability instead of sample flag in traceparent header for web requests

### ISSUE THREAD

**Issue by abalabolov** [micrometer-metrics/tracing#626]
**Issue: Overwhelm an application with tracing overhead**
https://www.w3.org/TR/trace-context-1/#denial-of-service

**Env:** Spring Boot 3.2.3, micrometer-tracing-bridge-otel + opentelemetry-exporter-zipkin
**System:** We have desktop, web client and monolitic server (for now) behind AWS ALB with autoscaling.

**What I would like to achive:**
1. The possibility to set `trace and span id` from any `Web client` and take them into account on the `BE` side for other internal purposes.
2. Make a final decision about Sampling on the `BE` side taking into account specified `probability` on the BE side and `SampleFlag` header from the `Web client` side. I.e. to follow this https://www.w3.org/TR/trace-context-1/#trace-flags

I set `tracing.sampling.probability: 0.1` and added `Aspect` (for testing purpose) that wraps several packages with the following code:
```
Span parentSpan = tracer.currentSpan();
Span newSpan = tracer.nextSpan(parentSpan)
	.name(SpanNameUtil.toLowerHyphen(methodName))
	.tag("class.name", className)
	.tag("input.params", Arrays.toString(parameters));

Object result;

try (Tracer.SpanInScope ws = this.tracer.withSpan(newSpan.start())) {
	result = joinPoint.proceed();
	
	if (nonNull(result)) {
		newSpan.tag("return.value", result.toString());
	}
}
finally {
	newSpan.end();
}
```

During startup I see that OTel creates `TraceIdRatioBasedSampler` and wraps it in `ParentBasedSampler`

**When I specify `traceparent header with sample flag = 01`, I face with the following:**
1. All web requests are catched in `PropagatingReceiverTracingObservationHandler.onStart()` that uses `parentTraceContext with `PropagatedSpan` with `traceFlags=01`.
3. Then `SpanBuilder.startSpan()` has `tracerSharedState` with `ParentBasedSampler` and calls `shouldSample()` on behalf of `ParentBasedSampler` that checks traceFlags from `PropagatedSpan`. So, it is more `SampleFlagBased` rather `parentBased`
4. `PropagatedSpan.traceFlags` = 01 so the decision is `RECORD_AND_SAMPLE` every time
5. If I specify `traceparent header with sample flag = 00`, then the result is `DROP` every time.
6. In any cases above, the `probability` doesn't make an effect. Even I set it to 0 or 0.0, all spans still appear in Zipkin

I think this behavior was implemented for comminication between isolated microservices. 

**So, my questions:**
1. How to prevent against attack from Web by calling our server with SampleFlag=01
2. How to make `probability` work with default out of the box settings
3. How to properly configure tracing to consider `probability` instead of `SampledFlag`
4. In case custom implementations, How to keep the possibility to support default behaviour for microservices. 

**I am loking for the right way to resolve them and think about one of the following:**
1.  **[Selected by me for now]** Create `Root OTel Sampler` with only `traceIdRatioBased` sampler. Trusting the following convention: if `Span` is considered to be `Sampled`, other calls to check `shouldSample` with the same params will return the same result. I have checked, this works as I described above.
```
@Bean
Sampler otelSampler() {
    return Sampler.traceIdRatioBased(0.10f);
}
```
2. Replace fields in `ParentBasedSampler`: remoteParentSampled(Sampler), localParentSampled(Sampler) to TraceIdRatioBasedSampler. Based on the "running the sampler on any child Span will produce the same decision"
3. Create own Sampler
4. Implement `OncePerRequest` filter and replace `SampleFlag` 01 to 00 if request is not from some "White list" that is loaded at startup to the memory. 
6. Implement custom `W3CTraceContextPropagator` and the same propagators: check if the header is allowed from the caller see option 4).

There is a topic that has the similar question but the answer is absent.
https://github.com/open-telemetry/opentelemetry-dotnet/issues/3594

**Comment by jonatan-ivanov** [comment]
>How to prevent against attack from Web by calling our server with SampleFlag=01

Can you force that your components will create the root span and not get the tracing info from some random source? I think requests from the public internet are from components that are not necessarily owned by you so they will not necessarily push data to your tracing backend so even if you get a header, you should drop it. You should be able to do this in an `API Gateway or Proxy`. You can also do more complicated things here like is the client trusted (so you keep the tracing info) or not (drop).

If you really want to do this directly in your app, you can write an (http servlet) filter that modifies the request headers before instrumentation would get and parse them so there is no need to modify the behavior of the tracer but you need to decide what data you trust as an input.

>How to make probability work with default out of the box settings

I'm not sure what you mean here, probability is taken into consideration when the root span is created (first component), after that the sampled flag decides. If this would not be like this, you would end up with incomplete traces (with probability 0.1 and lets say 10 spans in average, pretty much all the time).

>How to properly configure tracing to consider probability instead of SampledFlag

See above, I'm not sure you want this, let's say your trace looks like this:
```
A -> B -> C -> D -> E -> F -> G -> H -> I -> J
```
and your probability is 0.1. In this case it is very likely that most of your spans will be incomplete. Let's say for example that span A end up being `sampled=true`, then span B is created which ignores the sampled flag of span A, calculates the probability and span B ends up being `sampled=false`. So span A will be sent to your backend but span B won't, your trace is incomplete, it does not reflect the reality but it is basically just some random data.

>In case custom implementations, How to keep the possibility to support default behaviour for microservices.

I'm not sure I get this either.

Btw, you can also use server-side (tracing backend) sampling instead of client-side (your apps) sampling. This means that your apps will sample everything (probability = 1.0) but your tracing backend or an intermediate collector/proxy (e.g.: telegraf, otel collector) do the sampling before forwarding to the backend.

**Comment by shakuzen** [comment]
> How to prevent against attack from Web by calling our server with SampleFlag=01

I'll be reiterating what @jonatan-ivanov already explained, but it's a common principle in distributed tracing that you do not accept tracing data from untrusted sources for this reason. Things that act as a gateway that receive traffic from untrusted sources typically have the responsibility of dropping untrusted data and providing trusted data. In tracing, this means the tracing context via e.g. HTTP headers.

Are the clients outside of your backend system trusted clients? Are they producing spans or just a tracing context? Are you wanting the backend system to use the same ID for log correlation purposes only? It may be better to use a separate concept of a correlation ID that is not the trace ID or span ID.

**Comment by abalabolov** [comment]
@jonatan-ivanov @shakuzen Thank you for the anwers. I will give you some details since you were asking about them. Probably, you will update your answers then.

I understood that I need to keep some logic to protect incoming header and omit it by condition (f.ex., for not trusted devices).

`probability is taken into consideration when the root span is created (first component), after that the sampled flag decides`
Imagine the pretty simple env: Client -> Server (without microservices). Propability is taken into considiration, but `OTel` creates `TraceIdRatioBasedSampler`, wraps it in `ParentBasedSampler` and saves as a `ROOT` by default (see `OpenTelemetryAutoConfiguration`).

So, every time the requst comes, `ParentBasedSampler.shouldSample()` is called and checks:
1. when `parentSpanContext.isValid()==true`, then only `probability` is taken into account
2. when `parentSpanContext.isValid()==false`, then it takes `ROOT` sampler (where `isValid == true` every time) and goes to option "1".

What it the case when OTel ROOT Sampler is invalid?

`How to keep the possibility to support default behaviour for microservices.`
Here I was asking about protection against untrusted clients and bypassing it by trusted one. I got your answer thet I need to implement own at some layer (gateway, filter, etc.).

`Are the clients outside of your backend system trusted clients?`
Clients YES, but sender NO. So the answer is NO
It is our desktop or web apps, but requests can be performed using tools like Postman.

`Are they producing spans or just a tracing context? Are you wanting the backend system to use the same ID for log correlation purposes only?`
This is another question. The languages are different. Desktop is C++, Web is React. They have `correllationId` that is not used by our system) and my ide was to use that Id either as
1. `traceId` - then the request trace for FE will not be full
2. or as a `parentId` - in this case FE could create own spans and send to collector like Zipkin.

I think that It would be much simpler for a lot of your consumers if you create an example with the an obvious flow:
1. One frontend app: React, Html - no matter
2. One backend app: Java, C# - no matter. Important that app has several services layers, f.e.x.: `Controller -> Component 1 -> Service 1 -> call to external Service -> return to Service 1 -> return to Component 1 -> Service 2 -> Repo -> return to Service 2 -> return to Component 1 -> return to Controller`.
3. Config to trace (and measure) all the layers and allow to turn on/off them dynamically where possible.
This structure will force you to show how to manually create Spans (f.ex, using `@Aspect`).

Take a look at the very first one question to Marcin Grzejszczak & Tommy Ludwig: https://youtu.be/fh3VbrPvAjg?t=2516

**Comment by jonatan-ivanov** [comment]
>I perfomed acceptance test several times with generated traceId and parentId each request + probability = 0.1 + sample flag = 01. The test makes ~15 calls to the server. And 100% Spans from the reqeusts got to Zipkin. Then I changed sample flag = 00 and no one Span got to Zipkin.

That's the expected behavior.

>I didn't have incompleted Spans per request. The request either was fully traced with all underlying Spans or it didn't exist at all.

In your `Client -> Server` setup, I assume the `Client` does not send spans to Zipkin so that's why you don't have incomplete spans, if it would, you would have incomplete spans.
In this case I don't understand why your client is even sending you a trace header since the client does not report spans to Zipkin, it is just feeding the `Server` with random data.

Based on my understanding about your setup what you should do is ignoring the client trace headers since it is the `Server` who needs to be in charge of creating the root span in your case. If your client would report those spans then you should not ignore this information and rely on the sampled flag otherwise you will end up with incomplete traces.

This is really important you can:
- Either accept the client's trace header but in that case the client should report spans to Zipkin and the server have to sample based on the sampled flag from the client.
- Or you ignore the client's trace header (it does not report spans anyway so what's the point) and let the server create the root span and make the sampling decision.

>I think that It would be much simpler for a lot of your consumers if you create an example with the an obvious flow

We do have these examples, check [micrometer-samples](https://github.com/micrometer-metrics/micrometer-samples). You can also take a look at [teahouse](https://github.com/jonatan-ivanov/teahouse), it is the app that Tommy and Marcin demoed in the talk you linked above and tea-service has a UI with Thymeleaf.
