### ISSUE TITLE
Add support for list values in tags in Span and SpanCustomizer

### ISSUE THREAD

**Issue by Jasz** [micrometer-metrics/tracing#785]
Currently, Span and SpanCustomizer support tags with String, boolean, long and double values. OpenTelemetry additionally supports lists of those four types. This feature request proposes adding support for lists of these types to Micrometer.

Unfortunately, it seems that Brave doesn't support lists. One solution would be to concatenate the lists to a String.

**Comment by jonatan-ivanov** [comment]
I'm not sure there is a huge concern from the point of view of the tracing library (as you said we can concatenate) but for me the big question is the backend (this is a concert for the OTel SDK too): what happens if your backend does not support lists for tag values (I would assume that most of them don't)?
OTLP supports array for attribute value but there are exporters that don't (e.g.: Zipkin).

Also, I don't see this (see [Span](https://javadoc.io/doc/io.opentelemetry/opentelemetry-api-trace/latest/io/opentelemetry/api/trace/Span.html)):
> OpenTelemetry additionally supports lists of those four types

Do you mean [this](https://javadoc.io/doc/io.opentelemetry/opentelemetry-api-trace/latest/io/opentelemetry/api/trace/Span.html#setAttribute(io.opentelemetry.api.common.AttributeKey,T)) or something else?
```java
<T> Span setAttribute​(AttributeKey<T> key, T value)
```

I guess right now you can do a `String.join`, what difference do you have on the backend side if you use a single concatenated `String` instead of a `List`?

**Comment by Jasz** [comment]
> what happens if your backend does not support lists for tag values?

For example the [OtelToZipkinSpanTransformer](https://github.com/open-telemetry/opentelemetry-java/blob/6fc1d216ca0f199670a1cc5b081ad764d4a043fb/exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/OtelToZipkinSpanTransformer.java#L213) creates a comma separated string.

> Do you mean [this](https://javadoc.io/doc/io.opentelemetry/opentelemetry-api-trace/latest/io/opentelemetry/api/trace/Span.html#setAttribute(io.opentelemetry.api.common.AttributeKey,T)) or something else?

Exactly this. The usage would be for example:

    .setAttribute(AttributeKey.stringArrayKey("example"), List.of("a", "b", "c"))

> what difference do you have on the backend side if you use a single concatenated String instead of a List?

Grafana Tempo has [experimental support for vParquet4](https://grafana.com/docs/tempo/latest/release-notes/v2-5/#new-vparquet4-block-format-experimental), which also adds support for searching through arrays.

**Comment by jonatan-ivanov** [comment]
Makes sense, do you want to open a PR for this?
I think it would be really similar to this change: https://github.com/micrometer-metrics/tracing/commit/0faf66fb75c9f6df0a197336271b50bfd8da6551

**Comment by shakuzen** [comment]
I'm curious if anyone has a need for this. We've held off on allowing multi-value tags in metrics (I think at the time only Datadog supported them), and so I'm curious why there would be any more need for it in tracing. Can anyone share some real world examples of what they (would) use it for?

> Unfortunately, it seems that Brave doesn't support lists. One solution would be to concatenate the lists to a String.

This sort of highlights the peril of introducing this. What's the expectation on querying a backend for multi-value tags that are a concatenated string because the format or backend don't support multi-value tags? Suddenly some tag values may have structure and no longer be opaque, but existing single-value tags might contain commas that aren't indicative of a multi-value tag.
