### ISSUE TITLE
micrometer-tracing-bom-RELEASE not found

### ISSUE THREAD

**Issue by guiramos** [micrometer-metrics/tracing#792]
Hello. 

My projects started to get this weird error couple days ago:

```
Could not find io.micrometer:micrometer-tracing-bom:RELEASE.
Required by:
    project :discovery
```    

We indeed added these dependencies to one of our projects but eventually removed:

```
    implementation(platform("io.micrometer:micrometer-tracing-bom:latest.release"))
    implementation("io.micrometer:micrometer-tracing")
    implementation("io.micrometer:micrometer-tracing-bridge-brave")
```

And now none of the projects can get built. 

Tried everything, deleting gradle caches, .m2 repos, etc, etc.

Can you PLEASE help?

**Comment by jonatan-ivanov** [comment]
Hi,

This can be an issue with:
1. The Maven repo you use
2. The project you have
3. The local environment (unlikely)

Let's try to troubleshoot these one-by-one.

## Maven repo

Please use `mavenCentral()` for your `repositories`:
```groovy
repositories {
	mavenCentral()
	// other internal repose could be used after it
}
```
This is the official repo we publish artifacts. Since metadata is available you can verify that there is no `RELEASE` version in it, see: [`micrometer-tracing-bom/maven-metadata.xml`](https://repo1.maven.org/maven2/io/micrometer/micrometer-tracing-bom/maven-metadata.xml)

## The project

It can happen that there is something weird with your project and it somehow messes this up, in order to rule this out please create a new one (`gradle init` can help) with the following contents of your `build.gradle`:
```gradle
plugins {
	id 'java'
}

repositories {
	mavenCentral()
}

dependencies {
	implementation(platform 'io.micrometer:micrometer-tracing-bom:latest.release')
	implementation 'io.micrometer:micrometer-tracing-bridge-brave'
}
```
Then run `./gradlew dependencies | grep micrometer` to see what is resolved.

## The local environment

Please try to remove the following directories (assuming your workdir is your project root):
```sh
rm -rf .gradle/ ~/.gradle/caches/build-cache-1/ ~/.gradle/caches/modules-2/files-2.1/io.micrometer/
```
Maybe kill the Gradle daemons:
```sh
./gradlew --stop # or maybe kill `pidof java`
```

Since it seems everything is ok with Maven Central, I doubt that issue has anything to do with Micrometer Tracing so let me close it.
